sonar.projectKey=digitalization_digi-document-converter
sonar.projectName=digi-document-converter
sonar.organization=mcodevisionaryorg
sonar.sources=src
sonar.tests=tests
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.sourceEncoding=UTF-8
